# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.TextField(max_length=30)),
                ('texto', models.TextField(max_length=500)),
                ('creacion_fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicacion_fecha', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
