# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='publicacion_fecha',
        ),
        migrations.AddField(
            model_name='comentario',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
